version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/expresstest/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
   ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
	- location: scripts/remove.sh
      timeout: 300
      runas: root
   ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root