version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/
hooks:
   BeforeInstall:
    - location: scripts/stop.sh
      runas: root
   AfterInstall:
    - location: scripts/start.sh
      runas: root